-- Cancelas, Martín.
-- Nicolau, Jorge.

-- Eliminación de todas las tablas: TMP, DWA, DWM, DQM, DP y MET.
-- Las tablas STG se eliminan durante el pipeline.

-- Tablas TMP
DROP TABLE IF EXISTS TMP_EmployeeTerritories;

DROP TABLE IF EXISTS TMP_OrderDetails;

DROP TABLE IF EXISTS TMP_Orders;

DROP TABLE IF EXISTS TMP_Products;

DROP TABLE IF EXISTS TMP_Shippers;

DROP TABLE IF EXISTS TMP_Suppliers;

DROP TABLE IF EXISTS TMP_Territories;

DROP TABLE IF EXISTS TMP_WorldData2023;

DROP TABLE IF EXISTS TMP_Categories;

DROP TABLE IF EXISTS TMP_Regions;

DROP TABLE IF EXISTS TMP_Customers;

DROP TABLE IF EXISTS TMP_Employees;


-- Tablas DWA
DROP TABLE IF EXISTS DWA_SalesFact;

DROP TABLE IF EXISTS DWA_DeliveriesFact;

DROP TABLE IF EXISTS DWA_Customers;

DROP TABLE IF EXISTS DWA_Products;

DROP TABLE IF EXISTS DWA_Employees;

DROP TABLE IF EXISTS DWA_Time;

DROP TABLE IF EXISTS DWA_WorldData2023;


-- Tablas DWM
DROP TABLE IF EXISTS DWM_Customers;

DROP TABLE IF EXISTS DWM_Employees;

DROP TABLE IF EXISTS DWM_Products;

DROP TABLE IF EXISTS DWM_WorldData2023;

DROP TABLE IF EXISTS DWM_SalesFact;

DROP TABLE IF EXISTS DWM_DeliveriesFact;


-- Tablas DQM
DROP TABLE IF EXISTS DQM_TableStatistics;

DROP TABLE IF EXISTS DQM_FieldIssues;

DROP TABLE IF EXISTS DQM_LoadResults;

DROP TABLE IF EXISTS DQM_IntegrityChecks;

DROP TABLE IF EXISTS DQM_ProcessAudit;


-- Tablas DP
DROP TABLE IF EXISTS DP_SalesByProductMonth;

DROP TABLE IF EXISTS DP_TopCustomersByRevenue;

DROP TABLE IF EXISTS DP_EmployeePerformance;

DROP TABLE IF EXISTS DP_ProductReturns;


-- Tablas MET
DROP TABLE IF EXISTS MET_Tables;

DROP TABLE IF EXISTS MET_Columns;

DROP TABLE IF EXISTS MET_Lineage;

DROP TABLE IF EXISTS MET_Executions;

DROP TABLE IF EXISTS MET_TableVersions;

DROP TABLE IF EXISTS MET_DataProducts;
